[package]
name = "lista-1"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "zad1"
path = "zad1.rs"

[[bin]]
name = "zad2"
path = "zad2.rs"

[[bin]]
name = "zad3"
path = "zad3.rs"

[[bin]]
name = "zad4"
path = "zad4.rs"


[dependencies]
# bit-set = "0.5.3"
# chrono = "0.4.23"
# either = "1.8.0"
# fancy-regex = "0.10.0"
# futures = "0.3.25"
# im = "15.1.0"
# itertools = "0.10.5"
# lazy_static = "1.4.0"
# num = { version = "0.4.0", features = ["rand"] }
# once_cell = "1.16.0"
rand = "0.8.5"
# regex = "1.7.0"
# serde = { version = "1.0.150", features = ["derive"] }
# serde_json = "1.0.89"
# text_io = "0.1.12"
# thiserror = "1.0.37"
# tokio = { version = "1.23.0", features = ["full"] }
# tokio-util = { version = "0.7.4", features = ["full"] }

[dev-dependencies]
# quickcheck = "1.0.3"
# quickcheck_macros = "1.0.0"
# float_eq = "1.0.1"